name: Node CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install npm dependencies and build for deployment
      run: |
        npm install
        npm build
      env:
        NODE_ENV: production
    - name: Deploy to Server
      uses: ./.github/actions/rsync
      env:
        HOST_NAME: ${{ secrets.HOST_NAME }}
        HOST_IP: ${{ secrets.HOST_IP }}
        HOST_FINGERPRINT: ${{ secrets.HOST_FINGERPRINT }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        HOST_USERNMAE: wmyoutrack
        HOST_DESTINATION: "/home/wmyoutrack/nodeapp/"
        FOLDER: "./"
        ARGS: "-avzr --delete"
